### PR TITLE
Issue 22

### PR DESCRIPTION
**Pull request by jhanreg11**
Added some slight changes at Ken's request:
1. created an arrow at bottom of landing screen to make scrolling down more obvious. Smooth scrolls to About TJEF on click.
2. changed Jared Hanson to be Secretary and not Ryan Perry, changed Ray Xu to be Junior Management not Manager
3. added small spacer above spotlight description & centered captions

### CODE REVIEW

**Comment by jaredhanson11** [comment]
I don't like the arrow. Ken requested the arrow? Either make it a different arrow that disappears when scrolled or something different. The current arrow looks bad.

**Comment by jhanreg11** [comment]
Ken wanted to make it more obvious to people that they should scroll down. He wanted to just move "About TJEF" into viewport on landing, I suggested arrow. If you want the title moved up I can do that or I'll just make the arrow dissapear whenever the landing screen isn't holding the entire viewport

**Comment by jaredhanson11** [comment]
Just remove the arrow for now, and rerequest my review. Then merge changes (without arrow) and let Ken that I didn't approve of the arrow nor moving about tjef up and that we'll investigate some different options that make scrolling more obvious.

**Comment by jaredhanson11** [comment]
I don't want this commented code to sit in our codebase and do nothing. Delete the code that shouldn't be merged to master. If needed, you can cut a new branch to store the changes so you don't lose them if they are added back eventually. Don't merge code that shouldn't be in master to master though.

**Comment by jaredhanson11** [comment]
Remove the landing-error css too. Again, unused code only causes confusion for someone else trying to maintain your codebase.

**Pull request merged**
